/*
* Generated file
*
* Generated from: yang module name: hello-world-SR2-impl yang module local name: hello-world-SR2-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Mar 30 00:55:33 CEST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.hello_world_SR2.impl;
public class HelloWorldModuleFactory extends org.opendaylight.controller.config.yang.config.hello_world_SR2.impl.AbstractHelloWorldModuleFactory {

}
